databases:
  - name: iihc_portal
    plan: free
    databaseName: iihc_portal
    user: pxel

services:
  - type: web
    plan: free
    name: iihc_database
    runtime: python
    buildCommand: "./build.sh"  # Ensure this script exists and is executable
    startCommand: "python -m gunicorn iihc_website_portal.asgi:application -k uvicorn.workers.UvicornWorker"

    envVars:  # Environment variables for the web service
      - key: DATABASE_URL
        fromDatabase:
          name: iihc_portal
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4