# Generated by Django 5.1.2 on 2024-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=30)),
                ('religion', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('learning_mode', models.CharField(blank=True, choices=[('Modular', 'Modular'), ('Face to Face', 'Face to Face'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('strand', models.CharField(blank=True, choices=[('STEM', 'STEM (Science, Technology, Engineering, Mathematics)'), ('ABM', 'ABM (Accountancy, Business, and Management)'), ('HUMSS', 'HUMSS (Humanities and Social Sciences)'), ('GAS', 'GAS (General Academic Strand)'), ('TVL', 'TVL (Technical-Vocational-Livelihood)')], max_length=20)),
                ('tvl_track', models.CharField(blank=True, choices=[('ICT', 'Information and Communications Technology (ICT)'), ('Home Economics', 'Home Economics'), ('Tourism', 'Tourism'), ('Agri-fishery Arts', 'Agri-fishery Arts (Soon)'), ('Industrial Arts', 'Industrial Arts (Soon)'), ('Entrepreneurship', 'Entrepreneurship (Soon)')], max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Wallet', 'Mobile Wallet')], max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
