# Generated by Django 5.1.2 on 2024-11-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learning_mode',
            field=models.CharField(blank=True, choices=[('Modular', 'Modular'), ('FacetoFace', 'Face to Face'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
