# Generated by Django 5.1.2 on 2024-12-01 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_student_learning_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='learning_mode',
            field=models.CharField(blank=True, choices=[('Modular', 'Modular'), ('Face to Face', 'Face to Face'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='user_studen_student_a521d1_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='user_studen_email_9e058d_idx'),
        ),
    ]
